### ISSUE TITLE
prebuilt binary with IP address loaded from xml ?

### ISSUE THREAD

**Issue by ofZach** [microcosm/ofxKinectV2-OSC#1]
This is a great addon but it would be even more awesome if there was a prebuilt binary that had the ability to load in IP addresses to send to from a text file, so you only have to worry about the receiving side.  I don't know my way around c# but that seems not super hard.  If I get somewhere, I'll send a PR...

**Comment by microcosm** [comment]
Yeah it's true. I might have time to do this some time during Jan - also totally open to PR

**Comment by microcosm** [comment]
I have updated the broadcaster, it now reads IP addresses from a CSV. Super-simple for now but should do for most users. Pre-built binary here:
https://github.com/microcosm/KinectV2-OSC/releases/download/v0.1.0/KinectV2-OSC.zip

More info here:
https://github.com/microcosm/KinectV2-OSC
